// @vitest-environment happy-dom

/**
 * Unit Tests: Launcher.
 *
 * The "coverage" case matters most here: `RESPARKABLE_NAV_GROUPS` still
 * carries "Ask Sparkey", but `tab-registry.ts` has no `chat` kind (Sparkey's
 * pane absorbs chat), so the launcher must silently drop that one tile
 * rather than offer something that does nothing on click. The focus case
 * defends the bug caught while building this file: `openTab()` targets
 * `focusedLeafId`, which is wrong whenever the launcher is showing in a pane
 * that isn't the focused one.
 *
 * The badge cases cover the one number that survived the nav rail's deletion.
 * Two things about it are easy to get wrong and invisible when they are: a
 * failed counts fetch must still render the picker (a badge is a decoration;
 * losing the only way to open anything over one is not), and the count must
 * reach a screen reader, since a purely visual badge is silent to the people
 * most likely to be relying on it.
 *
 * @see components/resparkable/workspace/launcher.tsx
 */

import { beforeEach, describe, expect, it, vi } from 'vitest';
import { render, screen, waitFor, within } from '@testing-library/react';
import userEvent from '@testing-library/user-event';

import { Launcher } from '@/components/resparkable/workspace/launcher';
import {
  useWorkspace,
  WorkspaceProvider,
} from '@/components/resparkable/workspace/workspace-context';
import { apiClient, APIClientError } from '@/lib/api/client';
import { RESPARKABLE_API } from '@/lib/framework/resparkable/api/endpoints';
import { listLeaves } from '@/lib/framework/resparkable/ui/workspace/split-tree';

vi.mock('@/lib/api/client', async () => {
  const actual = await vi.importActual<typeof import('@/lib/api/client')>('@/lib/api/client');
  return { ...actual, apiClient: { ...actual.apiClient, get: vi.fn() } };
});

/**
 * Splits off a second leaf and renders its Launcher — `splitLeaf`'s new-leaf
 * id is generated by the provider (`crypto.randomUUID()`), so it's read
 * back from state rather than assumed.
 */
function Harness(): React.ReactElement {
  const workspace = useWorkspace();
  const leaves = listLeaves(workspace.root);
  const newLeaf = leaves.find((leaf) => leaf.id !== 'root') ?? null;

  return (
    <div>
      <button onClick={() => workspace.splitLeaf('root', 'horizontal')}>split</button>
      <button onClick={() => workspace.focusLeaf('root')}>focus root</button>
      {newLeaf && <Launcher leafId={newLeaf.id} />}
      <div data-testid="focused-is-new-leaf">
        {String(newLeaf !== null && workspace.focusedLeafId === newLeaf.id)}
      </div>
      <div data-testid="new-leaf-tab-kinds">{newLeaf?.tabs.map((tab) => tab.kind).join(',')}</div>
    </div>
  );
}

function renderLauncher() {
  return render(
    <WorkspaceProvider>
      <Harness />
    </WorkspaceProvider>
  );
}

beforeEach(() => {
  window.localStorage.clear();
  vi.mocked(apiClient.get).mockReset();
  // Nothing waiting, unless a case says otherwise — a badge on every tile
  // would otherwise leak into the unrelated coverage/focus assertions.
  vi.mocked(apiClient.get).mockResolvedValue({ inbox: 0, connections: 0, openTasks: 0 });
});

describe('Launcher — page header', () => {
  it('shows the page-level title and blurb above the grouped tiles', async () => {
    const user = userEvent.setup();
    renderLauncher();
    await user.click(screen.getByText('split'));

    expect(screen.getByRole('heading', { name: 'Open a tab' })).toBeInTheDocument();
    expect(screen.getByText('Ask Sparkey, or pick a view')).toBeInTheDocument();
  });
});

describe('Launcher — coverage', () => {
  it('groups items exactly like the nav rail, minus chat', async () => {
    const user = userEvent.setup();
    renderLauncher();
    await user.click(screen.getByText('split'));

    for (const label of ['Daily', 'Organise', 'Knowledge', 'Manage']) {
      expect(screen.getByText(label)).toBeInTheDocument();
    }
    expect(screen.getByRole('button', { name: /Today/ })).toBeInTheDocument();
    expect(screen.getByRole('button', { name: /Projects/ })).toBeInTheDocument();
    // Chat has no tab kind (Sparkey absorbs it) — never offered as a tile.
    expect(screen.queryByRole('button', { name: /Ask Sparkey/ })).not.toBeInTheDocument();
  });

  it('renders each tile as icon-over-label only — no blurb underneath', async () => {
    const user = userEvent.setup();
    renderLauncher();
    await user.click(screen.getByText('split'));

    const todayTile = screen.getByRole('button', { name: 'Today' });
    expect(within(todayTile).getByText('Today')).toBeInTheDocument();
    // Tiles used to carry section-help.ts's one-line blurb underneath the
    // label — live review asked for that dropped, so the accessible name
    // is exactly the label, not the label plus a sentence after it.
    expect(todayTile).toHaveAccessibleName('Today');
  });
});

describe('Launcher — targets its own pane, not focusedLeafId', () => {
  it('opens a tile into its own pane while it is the focused one', async () => {
    const user = userEvent.setup();
    renderLauncher();
    await user.click(screen.getByText('split'));
    expect(screen.getByTestId('focused-is-new-leaf')).toHaveTextContent('true');

    await user.click(screen.getByRole('button', { name: /Projects/ }));

    expect(screen.getByTestId('new-leaf-tab-kinds')).toHaveTextContent('projects');
  });

  it('opens into its own pane, and refocuses it, even when focus moved away since the split', async () => {
    const user = userEvent.setup();
    renderLauncher();
    await user.click(screen.getByText('split'));

    // Move focus off the new leaf without touching its (still-mounted) launcher.
    await user.click(screen.getByText('focus root'));
    expect(screen.getByTestId('focused-is-new-leaf')).toHaveTextContent('false');

    await user.click(screen.getByRole('button', { name: /Goals/ }));

    // Without the fix, this tab would have landed in 'root' instead.
    expect(screen.getByTestId('new-leaf-tab-kinds')).toHaveTextContent('goals');
    expect(screen.getByTestId('focused-is-new-leaf')).toHaveTextContent('true');
  });
});

describe('Launcher — the inbox badge', () => {
  it('fetches the counts endpoint', async () => {
    const user = userEvent.setup();
    renderLauncher();
    await user.click(screen.getByRole('button', { name: 'split' }));

    expect(apiClient.get).toHaveBeenCalledWith(RESPARKABLE_API.COUNTS);
  });

  it('names the count on the Inbox tile itself, so it is not silent to a screen reader', async () => {
    vi.mocked(apiClient.get).mockResolvedValue({ inbox: 7, connections: 3, openTasks: 12 });

    const user = userEvent.setup();
    renderLauncher();
    await user.click(screen.getByRole('button', { name: 'split' }));

    await waitFor(() =>
      expect(screen.getByRole('button', { name: /Inbox.*7 waiting/ })).toBeInTheDocument()
    );
  });

  it('shows no badge at zero — a count that never clears is one people stop seeing', async () => {
    const user = userEvent.setup();
    renderLauncher();
    await user.click(screen.getByRole('button', { name: 'split' }));

    await waitFor(() => expect(apiClient.get).toHaveBeenCalled());
    expect(screen.getByRole('button', { name: 'Inbox' })).toBeInTheDocument();
    expect(screen.queryByText(/waiting/)).not.toBeInTheDocument();
  });

  it('badges Inbox alone — Connections is the Activity pane\u2019s job now', async () => {
    vi.mocked(apiClient.get).mockResolvedValue({ inbox: 7, connections: 3, openTasks: 12 });

    const user = userEvent.setup();
    renderLauncher();
    await user.click(screen.getByRole('button', { name: 'split' }));

    await waitFor(() =>
      expect(screen.getByRole('button', { name: /Inbox.*7 waiting/ })).toBeInTheDocument()
    );
    expect(screen.getByRole('button', { name: 'Connections' })).toBeInTheDocument();
  });

  it('still renders every tile when the counts fetch fails', async () => {
    vi.mocked(apiClient.get).mockRejectedValue(new APIClientError('Down.', 'ERR', 500));

    const user = userEvent.setup();
    renderLauncher();
    await user.click(screen.getByRole('button', { name: 'split' }));

    await waitFor(() => expect(apiClient.get).toHaveBeenCalled());
    expect(screen.getByRole('button', { name: 'Inbox' })).toBeInTheDocument();
    expect(screen.getByRole('button', { name: 'Today' })).toBeInTheDocument();
  });
});
