/**
 * Unit Tests: Launcher.
 *
 * The "coverage" case matters most here: `RESPARKABLE_NAV_GROUPS` still
 * carries "Ask Sparkey", but `tab-registry.ts` has no `chat` kind (Sparkey's
 * pane absorbs chat), so the launcher must silently drop that one tile
 * rather than offer something that does nothing on click. The focus case
 * defends the bug caught while building this file: `openTab()` targets
 * `focusedLeafId`, which is wrong whenever the launcher is showing in a pane
 * that isn't the focused one.
 *
 * @see components/resparkable/workspace/launcher.tsx
 */

import { beforeEach, describe, expect, it } from 'vitest';
import { render, screen, within } from '@testing-library/react';
import userEvent from '@testing-library/user-event';

import { Launcher } from '@/components/resparkable/workspace/launcher';
import {
  useWorkspace,
  WorkspaceProvider,
} from '@/components/resparkable/workspace/workspace-context';
import { listLeaves } from '@/lib/framework/resparkable/ui/workspace/split-tree';

/**
 * Splits off a second leaf and renders its Launcher — `splitLeaf`'s new-leaf
 * id is generated by the provider (`crypto.randomUUID()`), so it's read
 * back from state rather than assumed.
 */
function Harness(): React.ReactElement {
  const workspace = useWorkspace();
  const leaves = listLeaves(workspace.root);
  const newLeaf = leaves.find((leaf) => leaf.id !== 'root') ?? null;

  return (
    <div>
      <button onClick={() => workspace.splitLeaf('root', 'horizontal')}>split</button>
      <button onClick={() => workspace.focusLeaf('root')}>focus root</button>
      {newLeaf && <Launcher leafId={newLeaf.id} />}
      <div data-testid="focused-is-new-leaf">
        {String(newLeaf !== null && workspace.focusedLeafId === newLeaf.id)}
      </div>
      <div data-testid="new-leaf-tab-kinds">{newLeaf?.tabs.map((tab) => tab.kind).join(',')}</div>
    </div>
  );
}

function renderLauncher() {
  return render(
    <WorkspaceProvider>
      <Harness />
    </WorkspaceProvider>
  );
}

beforeEach(() => {
  window.localStorage.clear();
});

describe('Launcher — coverage', () => {
  it('groups items exactly like the nav rail, minus chat', async () => {
    const user = userEvent.setup();
    renderLauncher();
    await user.click(screen.getByText('split'));

    for (const label of ['Daily', 'Organise', 'Knowledge', 'Manage']) {
      expect(screen.getByText(label)).toBeInTheDocument();
    }
    expect(screen.getByRole('button', { name: /Today/ })).toBeInTheDocument();
    expect(screen.getByRole('button', { name: /Projects/ })).toBeInTheDocument();
    // Chat has no tab kind (Sparkey absorbs it) — never offered as a tile.
    expect(screen.queryByRole('button', { name: /Ask Sparkey/ })).not.toBeInTheDocument();
  });

  it('shows each tile’s one-line blurb from section-help.ts', async () => {
    const user = userEvent.setup();
    renderLauncher();
    await user.click(screen.getByText('split'));

    const todayTile = screen.getByRole('button', { name: /Today/ });
    expect(within(todayTile).getByText(/ranked task list/i)).toBeInTheDocument();
  });
});

describe('Launcher — targets its own pane, not focusedLeafId', () => {
  it('opens a tile into its own pane while it is the focused one', async () => {
    const user = userEvent.setup();
    renderLauncher();
    await user.click(screen.getByText('split'));
    expect(screen.getByTestId('focused-is-new-leaf')).toHaveTextContent('true');

    await user.click(screen.getByRole('button', { name: /Projects/ }));

    expect(screen.getByTestId('new-leaf-tab-kinds')).toHaveTextContent('projects');
  });

  it('opens into its own pane, and refocuses it, even when focus moved away since the split', async () => {
    const user = userEvent.setup();
    renderLauncher();
    await user.click(screen.getByText('split'));

    // Move focus off the new leaf without touching its (still-mounted) launcher.
    await user.click(screen.getByText('focus root'));
    expect(screen.getByTestId('focused-is-new-leaf')).toHaveTextContent('false');

    await user.click(screen.getByRole('button', { name: /Goals/ }));

    // Without the fix, this tab would have landed in 'root' instead.
    expect(screen.getByTestId('new-leaf-tab-kinds')).toHaveTextContent('goals');
    expect(screen.getByTestId('focused-is-new-leaf')).toHaveTextContent('true');
  });
});
