/**
 * GET  /api/v1/resparkable/groups: the groups this person is in.
 * POST /api/v1/resparkable/groups: create one, and the workspace it owns.
 *
 * **Hand-written rather than generated by `createCollectionHandlers`.** That
 * generator mints a `spaceScope(session.user.id)` and hands it to a repo
 * function, which is exactly right for the twenty surfaces inside one person's
 * brain and exactly wrong here: a group is not in anybody's space, and the whole
 * question these routes answer is which space the caller may reach. The grants
 * routes are hand-written for the same reason and are the shape to copy.
 *
 * **A group is a principal, not a possession.** Creating one mints a space with
 * no owner (§23.2), so `POST` is the one route in the tier that brings a
 * `ResparkableSpace` into existence without a person attached to it. The service
 * is what guarantees that; the route only decides who may ask.
 *
 * Authentication: required. Rate limiting: the section's 100/min from
 * `proxy.ts`. Only the invite route needs a sub-cap, because only it sends mail.
 */

import { getRouteLogger } from '@/lib/api/context';
import { successResponse } from '@/lib/api/responses';
import { validateRequestBody } from '@/lib/api/validation';
import { withAuth } from '@/lib/auth/guards';
import { createGroup, listGroupsForActor } from '@/lib/framework/resparkable/services/membership';
import { createGroupSchema } from '@/lib/framework/resparkable/validations';

export const GET = withAuth(async (request, session) => {
  const log = await getRouteLogger(request);

  const memberships = await listGroupsForActor(session.user.id);

  log.info('Resparkable groups list', { count: memberships.length });

  // An allowlisted projection rather than the rows. `spaceId` is included
  // deliberately: it is what the switcher puts in the URL, and a member holding
  // it can do nothing a non-member could not, because every request re-resolves
  // membership through the one resolver. `inboxToken` and everything else on the
  // space row stays where it is.
  return successResponse(
    memberships.map((membership) => ({
      groupId: membership.groupId,
      name: membership.group.name,
      slug: membership.group.slug,
      description: membership.group.description,
      spaceId: membership.group.spaceId,
      role: membership.role,
      // Null means a request to join still waiting on an admin (§23.11). The
      // client renders it as pending rather than hiding the row: a person who
      // asked to join should see that they asked.
      joinedAt: membership.joinedAt,
    })),
    { count: memberships.length }
  );
});

export const POST = withAuth(async (request, session) => {
  const log = await getRouteLogger(request);

  const body = await validateRequestBody(request, createGroupSchema);

  const created = await createGroup(session.user.id, body);

  // No group name in the log line. It is a shared object other people can be
  // identified through, and this line outlives the group.
  log.info('Resparkable group created', { groupId: created.groupId });

  return successResponse(
    {
      groupId: created.groupId,
      name: created.group.name,
      slug: created.group.slug,
      spaceId: created.group.spaceId,
      role: created.role,
    },
    undefined,
    { status: 201 }
  );
});
